"""Album timeline dates

Revision ID: 55b3795585da
Revises: 56834a9da9d3
Create Date: 2024-07-06 10:06:48.931134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55b3795585da'
down_revision: Union[str, None] = '56834a9da9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('min_timestamp', sa.DateTime(), nullable=True))
    op.add_column('album', sa.Column('max_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('file', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('album', 'max_timestamp')
    op.drop_column('album', 'min_timestamp')
    # ### end Alembic commands ###
