"""Album thumbnails

Revision ID: 70fc1536eca7
Revises: 55b3795585da
Create Date: 2024-07-06 11:06:16.324066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70fc1536eca7'
down_revision: Union[str, None] = '55b3795585da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('thumbnail_file_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'thumbnail_file_id')
    # ### end Alembic commands ###
