"""File metadata

Revision ID: 7a768665a3e7
Revises: cceedb125b16
Create Date: 2024-06-11 20:55:53.987523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a768665a3e7'
down_revision: Union[str, None] = 'cceedb125b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filemeta_id'), 'filemeta', ['id'], unique=True)
    op.drop_column('file', 'height')
    op.drop_column('file', 'date_taken')
    op.drop_column('file', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('date_taken', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_filemeta_id'), table_name='filemeta')
    op.drop_table('filemeta')
    # ### end Alembic commands ###
