"""File timeline date

Revision ID: e14156a6b345
Revises: 7a768665a3e7
Create Date: 2024-06-11 20:57:28.900642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e14156a6b345'
down_revision: Union[str, None] = '7a768665a3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('timeline_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'timeline_date')
    # ### end Alembic commands ###
