"""Updated image metadata

Revision ID: f276328ba544
Revises: f9733c32f7cb
Create Date: 2024-06-05 05:21:24.376401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f276328ba544'
down_revision: Union[str, None] = 'f9733c32f7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('mimetype', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('photo', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('photo', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('photo', sa.Column('date_taken', sa.DateTime(), nullable=True))
    op.drop_column('photo', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('photo', 'date_taken')
    op.drop_column('photo', 'height')
    op.drop_column('photo', 'width')
    op.drop_column('photo', 'mimetype')
    # ### end Alembic commands ###
